### ISSUE TITLE
Green color in video

### ISSUE THREAD

**Issue by AnuraagKotnala** [am3n/RTSP-Client-Android#1]
On some devices, RTSP stream shows green color in video. Any solution for this? 

![2023-01-19-155648](https://user-images.githubusercontent.com/52658619/213980232-fe611aae-6b09-43ff-9ccf-767fedd416bc.jpeg)

**Comment by am3n** [comment]
Hi, what do you mean by device? Is there a frame problem on some mobiles or some cameras?

**Comment by AnuraagKotnala** [comment]
frame problem is in some mobiles i think. i know i dont have much more information regarding this, as video streaming from camera is giving .H264 codec only.

**Comment by am3n** [comment]
I have seen this problem in situations such as the size not being appropriate when decoding or the codec being incorrect.
First, please send the part of the code that is related to the setup and use of this library so that we can go step by step and solve the problem.
You may need to send me a `YUV Byte-Array` frame.

**Comment by andreyshmelev** [comment]
it is a yuv planes problem.
On some devices it decodes yuv frame wrong.
I use NV21 decode by OpenCV or you can decode it by other library
